import logging
import os
from pathlib import Path
from github import Github, GithubException

logger = logging.getLogger(__name__)

class GitHubReporter:
    """Generates markdown reports and creates GitHub issues/PRs."""

    def __init__(self, output_dir: str, github_repo: str = None):
        self.output_dir = Path(output_dir)
        self.github_repo = github_repo

        token = os.getenv("GITHUB_TOKEN")
        if token:
            self.github = Github(token)
        else:
            self.github = None
            if self.github_repo:
                logger.warning("GITHUB_TOKEN not found. Cannot create issues programmatically.")

    def generate_report(self, findings: list, target_repo: str):
        """Generates a polished Markdown report evaluating tools and findings."""
        report_path = self.output_dir / f"{target_repo}_security_sprint_report.md"

        logger.info(f"Generating Security Sprint Report at {report_path}...")

        with open(report_path, "w") as f:
            f.write(f"# AppSec Sprint Evaluation: {target_repo}\n\n")
            f.write("## Overview\n")
            f.write("This report evaluates the state of open source security tooling against Project Jupyter, specifically looking at how modern tools integrate into the SDLC, handle false positives, and whether they align with OSS philosophies.\n\n")

            f.write("### Open Questions Evaluated:\n")
            f.write("- **Has tooling kept up?** Yes, modern tools like Semgrep and AI-assisted triage significantly reduce noise compared to traditional AST scanners (like Bandit).\n")
            f.write("- **Is it compatible with OSS philosophies?** Tools that allow custom rules (Semgrep) and transparent AI integrations fit well within collaborative OSS workflows, enabling developers to actively contribute to security policies.\n\n")

            f.write(f"## Actionable Findings ({len(findings)})\n\n")

            for idx, finding in enumerate(findings):
                f.write(f"### {idx + 1}. [{finding.severity}] {finding.tool.upper()}: {finding.issue_id}\n")
                f.write(f"**Location:** `{finding.file_path}:{finding.line_number}`\n\n")
                f.write(f"**Description:** {finding.description}\n\n")

                ai_analysis = finding.raw_data.get('ai_analysis', {})
                if not ai_analysis.get('is_false_positive', False):
                    suggested_fix = ai_analysis.get('suggested_fix', 'Manual review required.')
                    f.write(f"**AI Suggested Fix:**\n```python\n{suggested_fix}\n```\n\n")

                f.write("---\n")

        logger.info("Report generation complete.")

    def create_draft_issues(self, findings: list):
        """Uses PyGithub to open draft issues on the target repository."""
        if not self.github or not self.github_repo:
            return

        try:
            repo = self.github.get_repo(self.github_repo)

            # For proof of concept, just create one aggregate issue or a few high priority ones
            high_findings = [f for f in findings if f.severity == "HIGH"]

            if not high_findings:
                logger.info("No HIGH severity findings to open issues for.")
                return

            title = f"[Security Tooling Sprint] Address {len(high_findings)} High-Severity Static Analysis Findings"

            body = "This issue was automatically generated during the Jupyter Security Tooling Sprint.\n\n"
            body += "### Findings to Address:\n"

            for f in high_findings:
                body += f"- **{f.file_path}:{f.line_number}** - {f.description} (Found by {f.tool})\n"

            body += "\n### Next Steps\n"
            body += "Review these findings and apply the suggested fixes generated by the AI triage engine."

            # Create the issue
            issue = repo.create_issue(title=title, body=body, labels=["security", "sprint-prep"])
            logger.info(f"Successfully created GitHub Issue: {issue.html_url}")

        except GithubException as e:
            logger.error(f"Failed to create GitHub issue: {e}")
